### ISSUE TITLE
Does not install root package.json

### ISSUE THREAD

**Issue by JackCA** [SocialGouv/yarn-workspace-focus-install#279]
I may be doing something wrong, but it appears that dependencies listed in the root package.json are not installed. Is there a way to install only these and the focused workspace? I frequently will put deps that all packages require like `jest` in the root package.json

**Comment by douglasduteil** [comment]
Hi @JackCA 
This tool has as goal the exact inverse : installing only dependencies required by a workspace.
This is why the root dependencies are always removed 
see https://github.com/SocialGouv/yarn-workspace-focus-install/blob/v1.1.25/src/install.ts#L66

**Comment by JackCA** [comment]
@douglasduteil yes fair enough -- see https://github.com/Madvinking/yarn-isolate-workspace/issues/16 for another issue I erroneously opened for a similar project.

I had originally thought that if all of my workspace packages had a common dependency (e.g. Typescript), I could keep them in sync by putting them in the root workspace. After using a few tools, including yarn 2, it looks like this is specifically not part of the design of workspaces. Although, I don't think I'm alone in thinking that that was one of the main features of workspaces.

Thanks for looking into this and appreciate your time ✌️
